'use strict';
const movies=[
{id:1,title:'Shadow House',year:2024,genre:['Anime'],rating:4.5,poster:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=900&q=85',desc:'Một bí ẩn mở ra trong căn nhà cổ, nơi những bí mật tưởng như đã ngủ quên bắt đầu thức tỉnh.',badges:['VIP','LT'],episodes:[1,2,3]},
{id:2,title:'Azure Pulse',year:2025,genre:['Khoa học viễn tưởng','Hành động'],rating:4.8,poster:'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=85',desc:'Trong tương lai gần, một nhóm hacker trẻ phát hiện ra AI đang âm thầm kiểm soát toàn bộ hạ tầng thành phố.',badges:['LT'],episodes:[1,2,3,4]},
{id:3,title:'Lạc Vào Giấc Mơ',year:2024,genre:['Tình cảm'],rating:4.6,poster:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=85',desc:'Một giấc mơ kỳ lạ kéo hai người xa lạ đến gần nhau hơn.',badges:['VIP'],episodes:[1,2]},
{id:4,title:'Your Lie in April',year:2015,genre:['Tình cảm','Âm nhạc'],rating:4.6,poster:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=85',desc:'Âm nhạc, tình bạn và những ngày tháng tuổi trẻ.',badges:['VIP','LT'],episodes:[1,2,3]},
{id:5,title:'Solo Leveling',year:2024,genre:['Hành động','Fantasy'],rating:4.9,poster:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85',desc:'Một thợ săn yếu nhất bắt đầu hành trình thay đổi số phận.',badges:['LT'],episodes:[1,2,3,4]},
{id:6,title:'Suzume',year:2022,genre:['Phiêu lưu'],rating:4.7,poster:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=85',desc:'Một cuộc hành trình kỳ diệu qua những cánh cửa bí ẩn.',badges:[],episodes:[1,2]},
{id:7,title:'Trái Tim Giấy',year:2023,genre:['Phim Việt','Tình cảm'],rating:5.0,poster:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85',desc:'Một câu chuyện nhẹ nhàng về những lựa chọn của tuổi trẻ.',badges:['VIP'],episodes:[1,2]},
{id:8,title:'Neon City',year:2025,genre:['Hành động','Khoa học viễn tưởng'],rating:4.4,poster:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85',desc:'Thành phố neon và cuộc chiến giành quyền kiểm soát dữ liệu.',badges:[],episodes:[1,2,3]}
];
const crew=[['MA','Miu Anh','Đỗ Minh Anh'],['HK','Huy Kai','Trần Gia Huy'],['VR','Vy Rin','Phạm Thảo'],['TT','Trà Tím','Nguyễn Trà']];
let user=readJSON('phimhayvietsub_user',null);
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function saveUser(u){user=u;localStorage.setItem('phimhayvietsub_user',JSON.stringify(u))}
function clearUser(){user=null;localStorage.removeItem('phimhayvietsub_user')}
function openModal(html){$('modalContent').innerHTML=html;$('modal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(){$('modal').classList.add('hidden');$('modalContent').innerHTML='';document.body.style.overflow=''}
function closeSearch(){ $('searchPanel').classList.add('hidden'); $('searchResults').innerHTML=''; document.body.style.overflow=''; }
function openSearch(){ $('searchPanel').classList.remove('hidden'); document.body.style.overflow='hidden'; setTimeout(()=>$('searchInput')?.focus(),0) }
function movieCard(m){return `<article class="movie"><button class="movie-open" data-id="${m.id}" style="display:block;width:100%;padding:0;border:0;background:none;text-align:left;color:inherit"><div class="poster" style="background-image:url('${esc(m.poster)}')"><div class="badges">${m.badges.map(b=>`<span class="badge ${b==='LT'?'lt':''}">${esc(b)}</span>`).join('')}</div><div class="poster-title">${esc(m.title)}</div><div class="rating">★ ${m.rating.toFixed(1)}</div></div><div class="movie-info"><h3>${esc(m.title)}</h3><p>${m.year} · ${m.genre.join(' · ')}</p></div></button></article>`}
function renderRails(){
 $('featuredRail').innerHTML=movies.slice(0,6).map(movieCard).join('');
 $('newRail').innerHTML=[...movies].sort((a,b)=>b.year-a.year).slice(0,6).map(movieCard).join('');
 document.querySelectorAll('.movie-open').forEach(b=>b.addEventListener('click',()=>showMovie(Number(b.dataset.id))));
}
function renderGenres(){const genres=[['MA','Tình cảm',''],['HK','Hành động',''],['VR','Phiêu lưu',''],['TT','Phim Việt','']];$('genreRail').innerHTML=genres.map(g=>`<button class="genre" data-genre="${esc(g[1])}" style="border:0;background:none;color:inherit;cursor:pointer"><span class="genre-icon">${g[0]}</span><b>${esc(g[1])}</b><small>Khám phá</small></button>`).join('');document.querySelectorAll('.genre').forEach(b=>b.addEventListener('click',()=>searchGenre(b.dataset.genre)))}
function renderCrew(){$('crewRail').innerHTML=crew.map(p=>`<div class="person"><div class="avatar">${esc(p[0])}</div><b>${esc(p[1])}</b><small>${esc(p[2])}</small></div>`).join('')}
function setHero(m){$('heroTitle').textContent=m.title;$('heroYear').textContent=m.year;$('heroGenre').textContent=m.genre.join(', ');$('heroRating').textContent=m.rating.toFixed(1);$('heroDesc').textContent=m.desc;document.querySelector('.hero').style.backgroundImage=`linear-gradient(90deg,rgba(5,8,20,.98) 0%,rgba(5,8,20,.74) 45%,rgba(5,8,20,.12) 100%),linear-gradient(0deg,#050814 0%,transparent 32%),url('${m.poster}')`;$('heroWatch').onclick=()=>showMovie(m.id);$('heroDetail').onclick=()=>showMovie(m.id)}
function showMovie(id){const m=movies.find(x=>x.id===id);if(!m)return;openModal(`<div class="movie-detail"><div class="detail-poster" style="background-image:url('${esc(m.poster)}')"></div><div><div class="eyebrow">🔥 PHIM NỔI BẬT</div><h2 class="auth-title">${esc(m.title)}</h2><p class="muted">${m.year} · ${esc(m.genre.join(' · '))} · ★ ${m.rating.toFixed(1)}</p><p class="muted">${esc(m.desc)}</p><h3>Danh sách tập</h3><div class="episodes">${m.episodes.map(n=>`<div class="episode"><span>Tập ${n}</span><button class="btn gradient" data-watch="${m.id}" data-episode="${n}">▶ Xem</button></div>`).join('')}</div></div></div>`);document.querySelectorAll('[data-watch]').forEach(b=>b.addEventListener('click',()=>watchEpisode(Number(b.dataset.watch),Number(b.dataset.episode))))}
function watchEpisode(id,n){const m=movies.find(x=>x.id===id);openModal(`<div class="eyebrow">ĐANG XEM</div><h2 class="auth-title">${esc(m.title)} — Tập ${n}</h2><div style="aspect-ratio:16/9;background:radial-gradient(circle,#192b55,#02050b);border:1px solid #2b3d70;border-radius:16px;display:grid;place-items:center;font-size:45px;color:#5d72a6">▶</div><p class="muted">Trình phát video mẫu. Khi có backend, thay khu vực này bằng video/HLS player.</p>`)}
function auth(mode='login'){const register=mode==='register';openModal(`<div><div class="eyebrow">PHIMHAYVIETSUB ACCOUNT</div><h2 class="auth-title">${register?'Tạo tài khoản mới':'Chào mừng trở lại'}</h2><p class="muted">${register?'Tạo tài khoản để lưu lịch sử xem, yêu thích và tham gia cộng đồng lồng tiếng.':'Đăng nhập để tiếp tục hành trình xem phim.'}</p><form id="authForm" class="form">${register?`<div class="field"><label>TÊN HIỂN THỊ</label><input id="name" minlength="2" required placeholder="Tên của bạn"></div>`:''}<div class="field"><label>EMAIL</label><input id="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>MẬT KHẨU</label><input id="password" type="password" minlength="6" required placeholder="Tối thiểu 6 ký tự"></div>${register?`<div class="field"><label>LOẠI TÀI KHOẢN</label><select id="role"><option value="USER">Thành viên</option><option value="VIP">VIP</option><option value="VOICE_ACTOR">Diễn viên lồng tiếng</option><option value="FILM_REVIEWER">Duyệt phim</option><option value="DIRECTOR">Đạo diễn</option></select></div>`:''}<div id="authMsg"></div><button class="submit" type="submit">${register?'Tạo tài khoản':'Đăng nhập'}</button><div class="divider">HOẶC</div><div id="googleButton"><button class="google" type="button" id="googleFallback">Đăng nhập bằng Google</button></div><p class="switch">${register?'Đã có tài khoản?':'Chưa có tài khoản?'} <button type="button" id="switchAuth">${register?'Đăng nhập':'Đăng ký'}</button></p></form></div>`);$('authForm').addEventListener('submit',register?registerAccount:loginAccount);$('switchAuth').addEventListener('click',()=>auth(register?'login':'register'));setTimeout(initGoogleLogin,100)}
function getAccounts(){return readJSON('phimhayvietsub_accounts',[])}
function registerAccount(e){e.preventDefault();const accounts=getAccounts(),email=$('email').value.trim().toLowerCase();if(accounts.some(x=>x.email===email)){return $('authMsg').innerHTML='<div class="error">Email này đã được đăng ký.</div>'}const u={id:Date.now(),name:$('name').value.trim(),email,role:$('role').value};accounts.push({...u,password:$('password').value});localStorage.setItem('phimhayvietsub_accounts',JSON.stringify(accounts));saveUser(u);closeModal();updateAccount()}
function loginAccount(e){e.preventDefault();const email=$('email').value.trim().toLowerCase(),p=$('password').value;const u=getAccounts().find(x=>x.email===email&&x.password===p);if(!u)return $('authMsg').innerHTML='<div class="error">Email hoặc mật khẩu không đúng.</div>';const {password,...safe}=u;saveUser(safe);closeModal();updateAccount()}
const GOOGLE_CLIENT_ID='YOUR_GOOGLE_CLIENT_ID.apps.googleusercontent.com';const GOOGLE_AUTH_ENDPOINT='/api/auth/google';
function initGoogleLogin(){const host=$('googleButton');if(!host)return;if(!window.google?.accounts?.id){setTimeout(initGoogleLogin,500);return}if(GOOGLE_CLIENT_ID.startsWith('YOUR_')){const b=$('googleFallback');if(b)b.addEventListener('click',()=>alert('Hãy cấu hình GOOGLE_CLIENT_ID và backend /api/auth/google trước khi dùng Google Login thật.'));return}host.innerHTML='';google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:handleGoogleCredential});google.accounts.id.renderButton(host,{theme:'outline',size:'large',width:320,text:'signin_with',shape:'rectangular'})}
async function handleGoogleCredential(response){try{const r=await fetch(GOOGLE_AUTH_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({credential:response.credential})});if(!r.ok)throw new Error('auth failed');const data=await r.json();if(!data.user)throw new Error('invalid response');saveUser(data.user);closeModal();updateAccount()}catch(err){const m=$('authMsg');if(m)m.innerHTML='<div class="error">Google Login chưa được kết nối với máy chủ.</div>';console.error(err)}}
function updateAccount(){if(user){$('loginBtn').textContent=user.name||'Tài khoản';$('registerBtn').textContent='Đăng xuất';$('registerBtn').onclick=()=>{clearUser();$('loginBtn').textContent='Đăng nhập';$('registerBtn').textContent='Đăng ký';$('registerBtn').onclick=()=>auth('register')}}else{$('loginBtn').textContent='Đăng nhập';$('registerBtn').textContent='Đăng ký';$('loginBtn').onclick=()=>auth('login');$('registerBtn').onclick=()=>auth('register')}}
function searchGenre(g){openSearch();$('searchInput').value=g;renderSearch(g)}
function renderSearch(q){const query=q.trim().toLowerCase();const result=movies.filter(m=>(m.title+' '+m.genre.join(' ')+' '+m.desc).toLowerCase().includes(query));$('searchResults').innerHTML=result.length?result.map(m=>`<div class="search-result"><button data-result="${m.id}"><b>${esc(m.title)}</b><br><span class="muted">${m.year} · ${esc(m.genre.join(' · '))}</span></button></div>`).join(''):'<p class="muted">Không tìm thấy phim.</p>';document.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>{closeSearch();showMovie(Number(b.dataset.result))}))}
$('menuBtn').addEventListener('click',()=>{const n=$('mainNav');const open=n.style.display==='flex';n.style.display=open?'none':'flex';$('menuBtn').setAttribute('aria-expanded',String(!open))});$('mainNav').querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{$('mainNav').style.display='none'}));$('searchBtn').addEventListener('click',openSearch);$('searchInput').addEventListener('input',e=>renderSearch(e.target.value));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeSearch()));$('searchPanel').addEventListener('click',e=>{if(e.target===$('searchPanel'))closeSearch()});$('modalClose').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeSearch();$('mainNav').style.display='none'}});$('loginBtn').onclick=()=>auth('login');$('registerBtn').onclick=()=>auth('register');$('accountBottom').onclick=()=>{if(!user){auth('login');return}openModal(`<div class="eyebrow">ACCOUNT</div><h2 class="auth-title">${esc(user.name)}</h2><p class="muted">${esc(user.email)} · ${esc(user.role)}</p><button class="btn gradient" id="logoutBtn">Đăng xuất</button>`);$('logoutBtn').addEventListener('click',()=>{clearUser();closeModal();updateAccount()})};document.addEventListener('click',e=>{const a=e.target.closest('.see-all');if(a&&a.dataset.scroll)document.getElementById(a.dataset.scroll).scrollIntoView({behavior:'smooth'})});
renderRails();renderGenres();renderCrew();setHero(movies[1]);updateAccount();
