const seed=[{id:1,title:'Shadow House',year:2026,genre:['Anime','Fantasy'],rating:4.7,poster:'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',desc:'Một bí ẩn mở ra trong căn nhà cổ.',director:'Caheoxanhle',episodes:[{n:1,title:'Cánh cửa đầu tiên',duration:'24:12'},{n:2,title:'Bóng tối thức tỉnh',duration:'25:03'},{n:3,title:'Tập đặc biệt',duration:'31:10',special:true,markers:[['00:30','Nhân vật A xuất hiện'],['02:15','Cảnh quan trọng'],['05:40','Bắt đầu thoại']]}]},{id:2,title:'Ocean Beyond',year:2026,genre:['Phiêu lưu','Fantasy'],rating:4.4,poster:'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80',desc:'Hành trình vượt đại dương.',director:'Miu',episodes:[{n:1,title:'Khởi hành',duration:'22:40'}]},{id:3,title:'Neon City',year:2025,genre:['Hành động','Khoa học viễn tưởng'],rating:4.2,poster:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=800&q=80',desc:'Thành phố tương lai.',director:'Hikari',episodes:[{n:1,title:'Đêm neon',duration:'26:10'}]}];
let data=JSON.parse(localStorage.getItem('phim_v3')||'null')||seed,user=JSON.parse(localStorage.getItem('user_v3')||'null');
const E=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('phim_v3',JSON.stringify(data))}
function render(){let gs=[...new Set(data.flatMap(x=>x.genre))];E('filter').innerHTML='<option value="">Tất cả thể loại</option>'+gs.map(x=>`<option>${esc(x)}</option>`).join('');E('chips').innerHTML=gs.map(x=>`<button class="chip" onclick="filter('${esc(x)}')">${esc(x)}</button>`).join('');renderMovies(data);E('crewGrid').innerHTML=[['Caheoxanhle','Đạo diễn'],['Miu','Diễn viên lồng tiếng'],['Hikari','Đạo diễn'],['Luna','Diễn viên lồng tiếng']].map(x=>`<div class="person"><div class="avatar">${x[0][0]}</div><b>${x[0]}</b><p>${x[1]}</p></div>`).join('');E('account').textContent=user?user.name:'Đăng nhập'}
function renderMovies(list){E('grid').innerHTML=list.map(m=>`<article class="card"><div class="poster" style="background-image:url('${m.poster}')"></div><div class="cardbody"><h3>${esc(m.title)}</h3><div class="muted">${m.year} · ${m.genre.join(' · ')} · ${m.episodes.length} tập</div><div class="stars">★ ${m.rating||0}</div><button onclick="movie(${m.id})">Xem chi tiết</button></div></article>`).join('')||'<p class="muted">Không tìm thấy phim.</p>'}
function filter(g){E('filter').value=g;renderMovies(g?data.filter(m=>m.genre.includes(g)):data)}
E('filter').onchange=e=>filter(e.target.value);E('search').oninput=e=>{let q=e.target.value.toLowerCase();renderMovies(data.filter(m=>(m.title+' '+m.genre.join(' ')+' '+m.director).toLowerCase().includes(q)))};
function close(){E('modal').classList.add('hidden')}
function auth(mode='login'){let r=mode==='register';E('content').innerHTML=`<div class="auth"><div class="intro"><label>PHIMHAY ACCOUNT</label><h2>${r?'Tham gia cộng đồng.':'Chào mừng trở lại.'}</h2><p>${r?'Tạo tài khoản để lưu lịch sử, đánh giá và tham gia hệ sinh thái lồng tiếng.':'Đăng nhập để tiếp tục hành trình xem phim.'}</p><div class="features"><span>✓ Đồng bộ lịch sử xem</span><span>✓ Yêu thích & đánh giá</span><span>✓ Thành viên / VIP / Crew</span></div></div><div class="authbox"><div class="tabs"><button class="${!r?'active':''}" onclick="auth('login')">Đăng nhập</button><button class="${r?'active':''}" onclick="auth('register')">Đăng ký</button></div>${r?regForm():loginForm()}</div></div>`;E('modal').classList.remove('hidden')}
function loginForm(){return `<form class="form" onsubmit="login(event)"><div class="field"><label>EMAIL</label><input id="email" type="email" placeholder="you@example.com" required></div><div class="field"><label>MẬT KHẨU</label><div class="pass"><input id="pass" type="password" minlength="6" required><button type="button" onclick="showpass()">Hiện</button></div></div><label class="check"><input type="checkbox"> Ghi nhớ đăng nhập</label><div id="msg"></div><button class="submit">Đăng nhập</button><div class="divider">HOẶC</div><div class="social"><button type="button" onclick="demo()">Tài khoản Demo</button><button type="button" onclick="alert('Google OAuth cần backend.')">Google</button></div><p class="switch">Chưa có tài khoản? <button type="button" onclick="auth('register')">Đăng ký</button></p></form>`}
function regForm(){return `<form class="form" onsubmit="register(event)"><div class="field"><label>TÊN HIỂN THỊ</label><input id="name" minlength="2" required placeholder="Tên của bạn"></div><div class="field"><label>EMAIL</label><input id="email" type="email" required placeholder="you@example.com"></div><div class="field"><label>MẬT KHẨU</label><div class="pass"><input id="pass" type="password" minlength="6" required placeholder="Tối thiểu 6 ký tự"><button type="button" onclick="showpass()">Hiện</button></div></div><div class="field"><label>LOẠI TÀI KHOẢN</label><select id="role"><option value="USER">Thành viên</option><option value="VIP">VIP</option><option value="VOICE_ACTOR">Diễn viên lồng tiếng</option><option value="FILM_REVIEWER">Duyệt phim</option><option value="DIRECTOR">Đạo diễn</option></select></div><label class="check"><input id="agree" type="checkbox" required> Tôi đồng ý với điều khoản.</label><div id="msg"></div><button class="submit">Tạo tài khoản</button><p class="switch">Đã có tài khoản? <button type="button" onclick="auth('login')">Đăng nhập</button></p></form>`}
function showpass(){let p=E('pass');p.type=p.type==='password'?'text':'password'}
function users(){return JSON.parse(localStorage.getItem('users_v3')||'[]')}
function login(e){e.preventDefault();let u=users().find(x=>x.email===E('email').value.trim().toLowerCase()&&x.password===btoa(E('pass').value));if(!u){E('msg').innerHTML='<div class="error">Email hoặc mật khẩu không đúng.</div>';return}user=u;localStorage.setItem('user_v3',JSON.stringify(u));E('account').textContent=u.name;close();dashboard()}
function register(e){e.preventDefault();let list=users(),em=E('email').value.trim().toLowerCase();if(list.some(x=>x.email===em)){E('msg').innerHTML='<div class="error">Email này đã được đăng ký.</div>';return}let u={id:Date.now(),name:E('name').value.trim(),email:em,password:btoa(E('pass').value),role:E('role').value};list.push(u);localStorage.setItem('users_v3',JSON.stringify(list));user=u;localStorage.setItem('user_v3',JSON.stringify(u));E('account').textContent=u.name;close();dashboard()}
function demo(){user={name:'Demo User',email:'demo@phimhay.local',role:'USER'};localStorage.setItem('user_v3',JSON.stringify(user));E('account').textContent=user.name;close();dashboard()}
function dashboard(){E('content').innerHTML=`<label>ACCOUNT</label><h2>Tài khoản</h2><p class="muted">${esc(user.name)} · ${esc(user.email)} · ${esc(user.role)}</p><button class="primary" onclick="logout()">Đăng xuất</button>`;E('modal').classList.remove('hidden')}
function logout(){user=null;localStorage.removeItem('user_v3');E('account').textContent='Đăng nhập';close()}
function movie(id){let m=data.find(x=>x.id===id);E('content').innerHTML=`<label>${esc(m.genre[0])}</label><h2>${esc(m.title)}</h2><p class="muted">${esc(m.desc)}</p><p class="muted">Đạo diễn: ${esc(m.director)}</p><h3>Danh sách tập</h3>${m.episodes.map(e=>`<div class="episode"><span><b>Tập ${e.n}: ${esc(e.title)}</b><br><small class="muted">${e.duration}</small>${e.special?'<span class="marker">SPECIAL</span>':''}</span><button onclick="watch(${m.id},${e.n})">▶ Xem</button></div>`).join('')}`;E('modal').classList.remove('hidden')}
function watch(id,n){let m=data.find(x=>x.id===id),e=m.episodes.find(x=>x.n===n);E('content').innerHTML=`<label>${e.special?'TẬP ĐẶC BIỆT':'ĐANG XEM'}</label><h2>${esc(m.title)} — Tập ${n}</h2><div class="video">▶ VIDEO PLAYER / HLS</div><p class="muted">${esc(e.title)} · ${e.duration}</p>${e.markers?.length?'<h3>Mốc thời gian đạo diễn</h3>'+e.markers.map(x=>`<span class="marker">${x[0]} · ${esc(x[1])}</span>`).join(''):''}`}
function ask(){let q=E('question').value.trim();if(!q)return;E('log').innerHTML+=`<p class="user">${esc(q)}</p>`;let a=/fantasy|phiêu lưu/i.test(q)?'Phim liên quan: Shadow House và Ocean Beyond.':/đạo diễn/i.test(q)?'Đạo diễn có thể quản lý phim, tập, diễn viên và mốc thời gian.':'Bạn có thể dùng thanh tìm kiếm hoặc lọc theo thể loại.';E('log').innerHTML+=`<p class="bot">${a}</p>`;E('question').value=''}
render();